Update deployment.yaml

diff --git a/charts/oai-5g-ran/oai-nr-ue/templates/deployment.yaml b/charts/oai-5g-ran/oai-nr-ue/templates/deployment.yaml
--- a/charts/oai-5g-ran/oai-nr-ue/templates/deployment.yaml
+++ b/charts/oai-5g-ran/oai-nr-ue/templates/deployment.yaml
@@ -139,8 +139,14 @@ spec:
         {{- if .Values.start.traffic}}
         command: [ "/bin/bash", "-c" ]
         args: 
-          - RFSIM_IP_ADDRESS=\$(getent hosts \"\$RFSIM_HOST\" | awk '{print \$1}'); echo \"Resolved RFSIM_IP_ADDRESS: \$RFSIM_IP_ADDRESS\";
-            exec /usr/bin/iperf3 -c oai-traffic-server --time 0 -B "$RFSIM_IP_ADDRESS";
+          - |
+            RFSIM_IP_ADDRESS=\$(getent hosts "\$RFSIM_HOST" | awk '{print \$1}');
+            if [ -z "\$RFSIM_IP_ADDRESS" ]; then
+              echo "Error: Unable to resolve RFSIM_HOST (\$RFSIM_HOST) to an IP address.";
+              exit 1;
+            fi;
+            echo "Resolved RFSIM_IP_ADDRESS: \$RFSIM_IP_ADDRESS";
+            exec /usr/bin/iperf3 -c oai-traffic-server --time 0 -B "\$RFSIM_IP_ADDRESS";
         {{- else}}
         command:
           - /bin/sleep
